### ISSUE TITLE
Issue - White space

### ISSUE THREAD

**Issue by srdjastankovic** [alex64a/DeleteDuplicateCharacters#1]
Hi Aleksa,

White space is not threathed well, exmaple below
![issue](https://github.com/alex64a/DeleteDuplicateCharacters/assets/10706360/4c145508-8834-491b-9a5a-130cfe99bcba)

Additional comments:

- don't name var/class/func as character. Instead give name according it's purpose
- double check formating, e.g. line 33, separater return with empty line, for block of comment use /**/
- for easier usage make exmaple to run in loop

**Comment by alex64a** [comment]
Hi Srdjane, 

The issue with the white spaces has been corrected.

Additional:
* var/class/func are given names according to their purpose.
* formatting has been fixed.
* the program runs in loop for easier use. 

Thank you for notifying me about the mistakes, feel free to notify me if you find something else. Best wishes, 

Aleksa
